services:
  im-connector:
    container_name: im-connector
    image: harbor.cloud.infn.it/datacloud-middleware/im-connector:ci-python3.12
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file:
      - ../.env

  opa:
    image: openpolicyagent/opa
    container_name: opa
    ports:
      - 8181:8181
    volumes:
      - ../opa/data:/im_connector:ro
    command: run --server --log-level debug --addr 0.0.0.0:8181 /im_connector