import enum


class IMRequestType(str, enum.Enum):
    NONE = "none"
    LIST_USER_INFRASTRUCTURES = "/infrastructures"
    CREATE_INFRASTRUCTURE = "/infrastructures"
    IMPORT_INFRASTRUCTURE = "/infrastructures"
    LIST_INFRASTRUCTURE_VMS = "/infrastructures/{InfId}"
    ADD_RESOURCES_TO_INFRASTRUCTURE = "/infrastructures/{InfId}"
    DELETE_INFRASTRUCTURE = "/infrastructures/{InfId}"
    GET_INFRASTRUCTURE_STATE = "/infrastructures/{InfId}/state"
    GET_INFRASTRUCTURE_OUTPUTS = "/infrastructures/{InfId}/outputs"
    GET_INFRASTRUCTURE_CONTEXTUALIZATION_MESSAGE = "/infrastructures/{InfId}/contmsg"
    EXPORT_INFRASTRUCTURE = "/infrastructures/{InfId}/data"
    GET_INFRASTRUCTURE_CREATION_RADL = "/infrastructures/{InfId}/radl"
    GET_INFRASTRUCTURE_TOSCA_REPRESENTATION = "/infrastructures/{InfId}/tosca"
    GET_INFRASTRUCTURE_OWNERS_LIST = "/infrastructures/{InfId}/authorization"
    CHANGE_INFRASTRUCTURE_AUTHORIZATION_DATA = "/infrastructures/{InfId}/authorization"
    STOP_INFRASTRUCTURE = "/infrastructures/{InfId}/stop"
    START_INFRASTRUCTURE =  "/infrastructures/{InfId}/start"
    RECONFIGURE_INFRASTRUCTURE =  "/infrastructures/{InfId}/reconfigure"
    GET_VM_INFO = "/infrastructures/{InfId}/vms/{VMId}"
    ALTER_VM = "/infrastructures/{InfId}/vms/{VMId}"
    DELETE_VM = "/infrastructures/{InfId}/vms/{VMId}"
    GET_VM_CONTEXTUALIZATION_MESSAGE ="/infrastructures/{InfId}/vms/{VMId}/contmsg"
    GET_VM_PROPERTY = "/infrastructures/{InfId}/vms/{VMId}/{Property}"
    STOP_VM = "/infrastructures/{InfId}/vms/{VMId}/stop"
    START_VM = "/infrastructures/{InfId}/vms/{VMId}/start"
    REBOOT_VM = "/infrastructures/{InfId}/vms/{VMId}/reboot"
    CREATE_DISK_SNAPSHOT = "/infrastructures/{InfId}/vms/{VMId}/disks/{diskNum}/snapshot"
    GET_CLOUD_PROVIDER_AVAILABLE_IMAGES_LIST = "/clouds/{CloudId}/images"
    GET_CLOUD_PROVIDER_USER_QUOTAS = "/clouds/{CloudId}/quotas"
    GET_IM_SERVER_STATS = "/stats"
    GET_OAI_PMH_TOSCA_INFO = "/oai"
    VERSION = "/version"
    INFRASTRUCTURE_CHECK_METHOD = "-_check_method"
    INFID_CHECK_METHOD = "-_check_method"
    VMS_CHECK_METHOD = "-_check_method"
    AUTH_CHECK_METHOD = "-_check_method"
